linters:
  enable:
    - errcheck
    - gofmt
    - goimports
    - gosimple
    - govet
    - ineffassign
    - misspell
    - staticcheck
    - stylecheck
    - typecheck
    - unused

linters-settings:
  errcheck:
    check-type-assertions: true
  govet:
    check-shadowing: true
  goimports:
    local-prefixes: github.com/yourusername/globus-go-sdk
  misspell:
    locale: US

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck

  # Maximum issues count per one linter.
  max-issues-per-linter: 0

  # Maximum count of issues with the same text.
  max-same-issues: 0

run:
  # Timeout for analysis, e.g. 30s, 5m.
  timeout: 5m

  # Include test files.
  tests: true

  # Build tags to include in the analysis
  build-tags:
    - integration

  # Skip directories.
  skip-dirs:
    - "vendor"

  # Skip files.
  skip-files:
    - ".*\\.pb\\.go$"
    - ".*\\.gen\\.go$"