project_name: globus-go-sdk

before:
  hooks:
    - go mod tidy

builds:
  - id: cli
    main: ./cmd/globus-cli/main.go
    binary: globus-cli
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64
    ldflags:
      - -s -w -X github.com/scttfrdmn/globus-go-sdk/pkg/core.Version={{.Version}}

archives:
  - id: cli
    builds:
      - cli
    format: tar.gz
    format_overrides:
      - goos: windows
        format: zip
    name_template: "globus-cli_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - LICENSE
      - README.md
      - doc/guides/*.md

checksum:
  name_template: 'checksums.txt'
  algorithm: sha256

snapshot:
  name_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'
      - '^ci:'
      - Merge pull request
      - Merge branch

release:
  github:
    owner: scttfrdmn
    name: globus-go-sdk
  prerelease: auto
  draft: false
  name_template: "v{{ .Version }}"
  header: |
    ## Globus Go SDK v{{ .Version }}
    
    This is the {{ .Tag }} release of the Globus Go SDK.
    
    See the [changelog](./doc/project/changelog.md) for a full list of changes.
  
  footer: |
    ## Thanks to all contributors!
    
    * Run `globus-cli --version` to check the installed version
    * File issues at https://github.com/scttfrdmn/globus-go-sdk/issues