repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: check-merge-conflict

  - repo: https://github.com/golangci/golangci-lint
    rev: v1.54.1
    hooks:
      - id: golangci-lint
        args: [--config=.golangci.yml]

  - repo: https://github.com/dnephin/pre-commit-golang
    rev: v0.5.1
    hooks:
      - id: go-fmt
      - id: go-imports
      - id: go-unit-tests
      - id: go-mod-tidy

  - repo: local
    hooks:
      - id: license-check
        name: Check for license headers
        entry: scripts/check-license-headers.sh
        language: script
        types: [go]
        pass_filenames: false
        
      - id: go-sec
        name: Run gosec security scanner
        entry: gosec ./...
        language: system
        types: [go]
        pass_filenames: false
      
      - id: shellcheck
        name: ShellCheck
        entry: shellcheck
        language: system
        types: [shell]
        exclude: ".*/bats/.*"