name: CI

on:
  workflow_dispatch:
    inputs:
      run_all:
        description: 'Run all jobs'
        default: 'false'
        required: false
        type: boolean

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'
          cache: true
          
      - name: Get dependencies
        run: |
          go mod download
          go mod verify

      - name: Lint with golangci-lint
        uses: golangci/golangci-lint-action@v4
        with:
          version: latest
          args: --timeout 5m

  test:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: ['1.21', '1.22']
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go ${{ matrix.go-version }}
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
          cache: true

      - name: Get dependencies
        run: |
          go mod download
          go mod verify
          
      - name: Test
        run: go test -v -race -coverprofile=coverage.txt -covermode=atomic ./pkg/...

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          file: ./coverage.txt
          fail_ci_if_error: false
          token: ${{ secrets.CODECOV_TOKEN }}

  integration-test:
    name: Integration Tests
    runs-on: ubuntu-latest
    # Only run integration tests when secrets are available (PRs from forks won't have access)
    if: ${{ github.event_name == 'push' || github.event.pull_request.head.repo.full_name == github.repository }}
    env:
      GLOBUS_TEST_CLIENT_ID: ${{ secrets.GLOBUS_TEST_CLIENT_ID }}
      GLOBUS_TEST_CLIENT_SECRET: ${{ secrets.GLOBUS_TEST_CLIENT_SECRET }}
      GLOBUS_TEST_SOURCE_ENDPOINT_ID: ${{ secrets.GLOBUS_TEST_SOURCE_ENDPOINT_ID }}
      GLOBUS_TEST_DEST_ENDPOINT_ID: ${{ secrets.GLOBUS_TEST_DEST_ENDPOINT_ID }}
      GLOBUS_TEST_GROUP_ID: ${{ secrets.GLOBUS_TEST_GROUP_ID }}
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'
          cache: true
          
      - name: Get dependencies
        run: |
          go mod download
          go mod verify

      # Only run integration tests if secrets are available
      - name: Check for credentials
        id: check-secrets
        run: |
          if [[ -n "$GLOBUS_TEST_CLIENT_ID" && -n "$GLOBUS_TEST_CLIENT_SECRET" ]]; then
            echo "secrets_available=true" >> $GITHUB_OUTPUT
          else
            echo "secrets_available=false" >> $GITHUB_OUTPUT
          fi

      - name: Run integration tests
        if: steps.check-secrets.outputs.secrets_available == 'true'
        run: ./scripts/run_integration_tests.sh

      - name: Skip integration tests
        if: steps.check-secrets.outputs.secrets_available != 'true'
        run: |
          echo "Skipping integration tests because required secrets are not available"
          echo "Integration tests require GLOBUS_TEST_CLIENT_ID and GLOBUS_TEST_CLIENT_SECRET to be set as secrets"
          
      - name: Generate test summary
        if: steps.check-secrets.outputs.secrets_available == 'true'
        run: ./scripts/test_summary.sh