name: Documentation

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    paths:
      - '**.md'
      - 'doc/**'
      - '.github/workflows/docs.yml'

jobs:
  markdown-lint:
    name: Markdown Lint
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Install markdownlint-cli
      run: npm install -g markdownlint-cli

    - name: Run markdownlint
      run: markdownlint '**/*.md' --ignore node_modules --ignore vendor --config .github/workflows/markdownlint.yaml || true

  link-check:
    name: Check Links
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Install markdown-link-check
      run: npm install -g markdown-link-check

    - name: Check links in README
      run: markdown-link-check README.md

    - name: Check links in docs
      run: find doc -name "*.md" -exec markdown-link-check --config .github/workflows/mlc_config.json {} \; || true

  docs-build:
    name: Build Documentation
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.21'
        cache: true

    - name: Generate API docs with pkgsite
      run: |
        go install golang.org/x/pkgsite/cmd/pkgsite@latest
        mkdir -p api-docs
        pkgsite -open=false -dir=api-docs -templates=false ./pkg
        echo "API documentation generated in api-docs directory"