name: Security Scan

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 0 * * 0'  # Run weekly
  workflow_dispatch:  # Allow manual triggering

jobs:
  gosec:
    name: GoSec Security Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: '^1.18'

      - name: Install gosec
        run: |
          go install github.com/securego/gosec/v2/cmd/gosec@latest
      
      - name: Run gosec
        run: |
          gosec -fmt=json -out=gosec-results.json ./...
        continue-on-error: true  # Don't fail the build yet
        
      - name: Upload SARIF report
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: gosec-results.json
          
      - name: Check gosec results
        run: |
          ISSUES=$(cat gosec-results.json | jq '.Issues | length')
          if [ $ISSUES -gt 0 ]; then
            echo "GoSec found $ISSUES potential security issues"
            exit 1
          else
            echo "No security issues found by GoSec"
          fi
          
  nancy:
    name: Nancy Vulnerability Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: '^1.18'
          
      - name: Install Nancy
        run: |
          curl -sSfL https://raw.githubusercontent.com/sonatype-nexus-community/nancy/master/scripts/install-nancy.sh | sh -s -- -b $(go env GOPATH)/bin
          
      - name: Run Nancy
        run: |
          go list -json -m all | nancy sleuth
          
  gitleaks:
    name: Gitleaks Secrets Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          
      - name: Install Gitleaks
        run: |
          wget https://github.com/zricethezav/gitleaks/releases/download/v8.8.8/gitleaks_8.8.8_linux_x64.tar.gz
          tar -xzf gitleaks_8.8.8_linux_x64.tar.gz
          chmod +x gitleaks
          sudo mv gitleaks /usr/local/bin/
          
      - name: Run Gitleaks
        run: |
          gitleaks detect --report-format json --report-path gitleaks-report.json
        continue-on-error: true  # Don't fail the build yet
          
      - name: Check Gitleaks results
        run: |
          if [ -s gitleaks-report.json ]; then
            echo "Gitleaks found potential secrets in the codebase"
            cat gitleaks-report.json
            exit 1
          else
            echo "No secrets found by Gitleaks"
          fi